### ISSUE TITLE
TypeError: The data type of 'input' in one_hot must be ['int32', 'int64'], but received float32. 

### ISSUE THREAD

**Issue by liu4791959** [gujingxiao/Lane-Segmentation-Solution-For-Baidu-PaddlePaddle-Autonomous-Driving-Competition#18]
(paddle) speed@speed:~/liulei/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition-master$ python train.py
TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure TensorRT dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;Train Data Size: 19871
(-1, 256, 32, 96)
(-1, 256, 32, 96)
(-1, 768, 32, 96)
(-1, 192, 32, 96)
(-1, 160, 64, 192)
(-1, 80, 256, 768)
(-1, 8, 512, 1536)
The program will run deeplabv3p
Traceback (most recent call last):
  File "train.py", line 145, in <module>
    main()
  File "train.py", line 90, in main
    reduced_loss, miou, pred = create_network(images, labels, num_classes, network=network, image_size=(IMG_SIZE[1], IMG_SIZE[0]), for_test=False)
  File "train.py", line 50, in create_network
    loss, miou = create_loss(predict, train_label, classes)
  File "train.py", line 32, in create_loss
    dice_loss = fluid.layers.dice_loss(predict, label)
  File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8318, in dice_loss
    label = one_hot(label, depth=input.shape[-1])
  File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7228, in one_hot
    check_variable_and_dtype(input, 'input', ['int32', 'int64'], 'one_hot')
  File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
    check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
  File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
    extra_message))
TypeError: The data type of 'input' in one_hot must be ['int32', 'int64'], but received float32. 
请问该如何解决该问题

**Comment by gujingxiao** [comment]
> (paddle) speed@speed:~/liulei/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition-master$ python train.py
> TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
> Suggestions:
> 
> 1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
> 2. Configure TensorRT dynamic library environment variables as follows:
> 
> * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> * Windows: set PATH by `set PATH=XXX;Train Data Size: 19871
>   (-1, 256, 32, 96)
>   (-1, 256, 32, 96)
>   (-1, 768, 32, 96)
>   (-1, 192, 32, 96)
>   (-1, 160, 64, 192)
>   (-1, 80, 256, 768)
>   (-1, 8, 512, 1536)
>   The program will run deeplabv3p
>   Traceback (most recent call last):
>   File "train.py", line 145, in 
>   main()
>   File "train.py", line 90, in main
>   reduced_loss, miou, pred = create_network(images, labels, num_classes, network=network, image_size=(IMG_SIZE[1], IMG_SIZE[0]), for_test=False)
>   File "train.py", line 50, in create_network
>   loss, miou = create_loss(predict, train_label, classes)
>   File "train.py", line 32, in create_loss
>   dice_loss = fluid.layers.dice_loss(predict, label)
>   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8318, in dice_loss
>   label = one_hot(label, depth=input.shape[-1])
>   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7228, in one_hot
>   check_variable_and_dtype(input, 'input', ['int32', 'int64'], 'one_hot')
>   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
>   check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
>   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
>   extra_message))
>   TypeError: The data type of 'input' in one_hot must be ['int32', 'int64'], but received float32.
>   请问该如何解决该问题

你好，上面提示的错误很明显，label的输入必须是int32和int64的类型，但是你传入的却是float32的类型，导致报错。请把one_hot形式的了label数据改为int32即可。

因为这个工程是基于PaddlePaddle 0.4.0版本搭建的，而现在已经到了2.0版本，有很多地方不一样了，所以还需要根据PaddlePaddle版本做一些相应的修改。

**Comment by shoushangdetuolaji** [comment]
你好，作者。**_请把one_hot形式的了label数据改为int32即可。_**  我大概了解意思跟据`nn.py` 修改好像就报相同的错。
这是nn.py的程序
`
def one_hot(input, depth, allow_out_of_range=False):
    """

    **WARING:** This OP requires the last dimension of Tensor shape must be equal to 1.
    This OP will be deprecated in a future release. It is recommended to use fluid. :ref:`api_fluid_one_hot` .

    The operator converts each id in the input to an one-hot vector with a
    :attr:`depth` length. The value in the vector dimension corresponding to the id
    is 1, and the value in the remaining dimension is 0.

    The shape of output Tensor or LoDTensor is generated by adding :attr:`depth` dimension
    behind the last dimension of the input shape.

    .. code-block:: text

        Example 1 (allow_out_of_range=False):

        input:
            X.shape = [4, 1]
            X.data = [[1], [1], [3], [0]]
            depth = 4

        output:
            Out.shape = [4, 4]
            Out.data = [[0., 1., 0., 0.],
                        [0., 1., 0., 0.],
                        [0., 0., 0., 1.],
                        [1., 0., 0., 0.]]

        Example 2 (allow_out_of_range=True):

        input:
            X.shape = [4, 1]
            X.data = [[1], [1], [5], [0]]
            depth = 4
            allow_out_of_range = True

        output:
            Out.shape = [4, 4]
            Out.data = [[0., 1., 0., 0.],
                        [0., 1., 0., 0.],
                        [0., 0., 0., 0.], # This id is 5, which goes beyond depth, so set it all-zeros data.
                        [1., 0., 0., 0.]]

        Example 3 (allow_out_of_range=False):

        input:
            X.shape = [4, 1]
            X.data = [[1], [1], [5], [0]]
            depth = 4
            allow_out_of_range = False

        output: Throw an exception for Illegal value
            The second dimension in X is 5, which is greater than depth.
            Allow_out_of_range =False means that does not allow the word id to exceed depth,
            so it throws an exception.

    Args:
        input(Variable): Tensor or LoDTensor with shape :math:`[N_1, N_2, ..., N_k, 1]` ,
            which contains at least one dimension and the last dimension must be 1.
            The data type is int32 or int64.
        depth(scalar): An integer defining the :attr:`depth` of the one hot dimension. If input
            is word id, depth is generally the dictionary size.
        allow_out_of_range(bool): A bool value indicating whether the input
            indices could be out of range :math:`[0, depth)` . When input indices are
            out of range, exceptions :code:`Illegal value` is raised if :attr:`allow_out_of_range`
            is False, or zero-filling representations is created if it is set True.
            Default: False.

    Returns:
        Variable: The one-hot representations of input. A Tensor or LoDTensor with type float32.

    Examples:
        .. code-block:: python

            import paddle.fluid as fluid
            # Correspond to the first example above, where label.shape is [4, 1] and one_hot_label.shape is [4, 4].
            label = fluid.data(name="label", shape=[4, 1], dtype="int64")
            one_hot_label = fluid.layers.one_hot(input=label, depth=4)
    """
    if in_dygraph_mode():
        if isinstance(depth, Variable):
            depth = depth.numpy()
            assert depth.shape == (
                1, ), "depth of type Variable should have shape [1]"
            depth = depth[0]
        out = core.ops.one_hot(input, 'depth', depth, 'allow_out_of_range',
                               allow_out_of_range)
        out.stop_gradient = True
        return out

    helper = LayerHelper("one_hot", **locals())
    check_variable_and_dtype(input, 'input', ['int32', 'int64'], 'one_hot')
    check_type(depth, 'depth', (six.integer_types, Variable), 'one_hot')
    one_hot_out = helper.create_variable_for_type_inference(dtype='float32')

    if not isinstance(depth, Variable):
        # user attribute
        inputs = {'X': input}
        attrs = {'depth': depth, 'allow_out_of_range': allow_out_of_range}
    else:
        depth.stop_gradient = True
        inputs = {'X': input, 'depth_tensor': depth}
        attrs = {'allow_out_of_range': allow_out_of_range}
    helper.append_op(
        type="one_hot",
        inputs=inputs,
        attrs=attrs,
        outputs={'Out': one_hot_out})
    one_hot_out.stop_gradient = True
    return one_hot_out
`

**Comment by shoushangdetuolaji** [comment]
**_因为这个工程是基于PaddlePaddle 0.4.0版本搭建的，而现在已经到了2.0版本，有很多地方不一样了，所以还需要根据PaddlePaddle版本做一些相应的修改。_** 

我是按照readme那里依赖版本号安装的。。 paddlepaddle-gpu对应也是paddlepaddle-gpu 1.3.0.post97

**Comment by STRIVESS** [comment]
> > (paddle) speed@speed:~/liulei/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition-master$ python train.py
> > TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
> > Suggestions:
> > 
> > 1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
> > 2. Configure TensorRT dynamic library environment variables as follows:
> > 
> > 
> > * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> > * Windows: set PATH by `set PATH=XXX;Train Data Size: 19871
> >   (-1, 256, 32, 96)
> >   (-1, 256, 32, 96)
> >   (-1, 768, 32, 96)
> >   (-1, 192, 32, 96)
> >   (-1, 160, 64, 192)
> >   (-1, 80, 256, 768)
> >   (-1, 8, 512, 1536)
> >   The program will run deeplabv3p
> >   Traceback (most recent call last):
> >   File "train.py", line 145, in
> >   main()
> >   File "train.py", line 90, in main
> >   reduced_loss, miou, pred = create_network(images, labels, num_classes, network=network, image_size=(IMG_SIZE[1], IMG_SIZE[0]), for_test=False)
> >   File "train.py", line 50, in create_network
> >   loss, miou = create_loss(predict, train_label, classes)
> >   File "train.py", line 32, in create_loss
> >   dice_loss = fluid.layers.dice_loss(predict, label)
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8318, in dice_loss
> >   label = one_hot(label, depth=input.shape[-1])
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7228, in one_hot
> >   check_variable_and_dtype(input, 'input', ['int32', 'int64'], 'one_hot')
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
> >   check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
> >   extra_message))
> >   TypeError: The data type of 'input' in one_hot must be ['int32', 'int64'], but received float32.
> >   请问该如何解决该问题
> 
> 你好，上面提示的错误很明显，label的输入必须是int32和int64的类型，但是你传入的却是float32的类型，导致报错。请把one_hot形式的了label数据改为int32即可。
> 
> 因为这个工程是基于PaddlePaddle 0.4.0版本搭建的，而现在已经到了2.0版本，有很多地方不一样了，所以还需要根据PaddlePaddle版本做一些相应的修改。

顾先生，您好！我最近在做基于深度学习的车道线检测毕业设计，之前也浏览过你的博客相关技术文章，为你的创作能力点赞，由衷敬佩！我最近在电脑配置好环境，复现一下你的代码，我的环境是（Windows-7 64位+CUDA 9.0+cudnn v7.6.5.32+单卡GPU训练+paddle 2.0.0），运行了train.py文件之后，发现报同样的错误：label的输入必须是int32和int64的类型，但是你传入的却是float32的类型；请问把one_hot形式的了label数据改为int32

**Comment by STRIVESS** [comment]
> > (paddle) speed@speed:~/liulei/Lane-Segmentation-Solution-For-BaiduAI-Autonomous-Driving-Competition-master$ python train.py
> > TensorRT dynamic library (libnvinfer.so) that Paddle depends on is not configured correctly. (error code is libnvinfer.so: cannot open shared object file: No such file or directory)
> > Suggestions:
> > 
> > 1. Check if TensorRT is installed correctly and its version is matched with paddlepaddle you installed.
> > 2. Configure TensorRT dynamic library environment variables as follows:
> > 
> > 
> > * Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
> > * Windows: set PATH by `set PATH=XXX;Train Data Size: 19871
> >   (-1, 256, 32, 96)
> >   (-1, 256, 32, 96)
> >   (-1, 768, 32, 96)
> >   (-1, 192, 32, 96)
> >   (-1, 160, 64, 192)
> >   (-1, 80, 256, 768)
> >   (-1, 8, 512, 1536)
> >   The program will run deeplabv3p
> >   Traceback (most recent call last):
> >   File "train.py", line 145, in
> >   main()
> >   File "train.py", line 90, in main
> >   reduced_loss, miou, pred = create_network(images, labels, num_classes, network=network, image_size=(IMG_SIZE[1], IMG_SIZE[0]), for_test=False)
> >   File "train.py", line 50, in create_network
> >   loss, miou = create_loss(predict, train_label, classes)
> >   File "train.py", line 32, in create_loss
> >   dice_loss = fluid.layers.dice_loss(predict, label)
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 8318, in dice_loss
> >   label = one_hot(label, depth=input.shape[-1])
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7228, in one_hot
> >   check_variable_and_dtype(input, 'input', ['int32', 'int64'], 'one_hot')
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
> >   check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
> >   File "/home/speed/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 116, in check_dtype
> >   extra_message))
> >   TypeError: The data type of 'input' in one_hot must be ['int32', 'int64'], but received float32.
> >   请问该如何解决该问题
> 
> 你好，上面提示的错误很明显，label的输入必须是int32和int64的类型，但是你传入的却是float32的类型，导致报错。请把one_hot形式的了label数据改为int32即可。
> 
> 因为这个工程是基于PaddlePaddle 0.4.0版本搭建的，而现在已经到了2.0版本，有很多地方不一样了，所以还需要根据PaddlePaddle版本做一些相应的修改。

顾先生，您好！我最近在做基于深度学习的车道线检测毕业设计，之前也浏览过你的博客相关技术文章，为你的创作能力点赞，由衷敬佩！我最近在电脑配置好环境，复现一下你的代码，我的环境是（Windows-7 64位+CUDA 9.0+cudnn v7.6.5.32+单卡GPU训练+paddle 2.0.0），运行了train.py文件之后，发现报同样的错误：label的输入必须是int32和int64的类型，但是你传入的却是float32的类型；                                                                               
请问把one_hot形式的了label数据改为int32是指修改哪个文件中的代码？我刚刚打算修改nn.py文件中的函数def one_hot(input, depth, allow_out_of_range=False):里的one_hot_out = helper.create_variable_for_type_inference(dtype='float32')这句代码改为one_hot_out = helper.create_variable_for_type_inference(dtype='int32')，请问这样操作正确吗？
